const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('index.html','utf8').split('<script>')[1].split('</script>')[0];
const ctx={document:{getElementById:()=>({})},localStorage:{getItem:()=>null}};vm.createContext(ctx);
vm.runInContext(source.slice(0,source.indexOf('function optionsPanel('))+';globalThis.api={compile,candidates,solve,normalizeDimensions,normalizeInventory,normalizeSizeRules,normalizeBackup,makeBackup,planWeight,modelGeometry};',ctx);
const {compile,candidates,solve,normalizeInventory,normalizeSizeRules,normalizeDimensions,planWeight}=ctx.api;
const s={cl:5900,cw:2352,ch:2395,payload:20000,dw:2340,dh:2292,wall:30,gap:30,base:50,packing:20,minW:400,maxW:2200,maxWFRatio:1.5,maxF:2200,step:25,t:40,axial:0,c:50,k:.7,m:20,reserve:5,maxLevels:3,spacer:50,stackMode:'mixed',floorOrientation:'auto',capacityMode:'guarded'};
const barrel=compile('m*od',['m','od']),capacity=compile('k*W*((F-2*c)^2-B^2)/(1000*od^2)',['k','W','F','c','B','od']);
const item={name:'Cable',od:20,length:100,qty:2,kg:1,tare:90};
const fixed=(value,unit='mm')=>({mode:'fixed',unit,value:String(value)});
let options=candidates({...item,dimensions:{F:fixed(48,'in'),B:fixed(425.5)}},s,barrel,capacity);
assert.ok(options.length);assert.ok(options.every(d=>d.F===1219.1999999999998&&d.B===425.5));
options=candidates({...item,dimensions:{W:fixed(623.4),F:{mode:'options',unit:'in',value:'35, 40, 48'}}},s,barrel,capacity);
assert.ok(options.length);assert.ok(options.every(d=>d.W===623.4&&[35,40,48].some(n=>Math.abs(n*25.4-d.F)<1e-8)));
options=candidates({...item,dimensions:{F:{mode:'range',unit:'in',value:'35, 45, 5'},B:{mode:'options',unit:'mm',value:'425, 450'}}},s,barrel,capacity);
assert.ok(options.length);assert.ok(options.every(d=>[35,40,45].some(n=>Math.abs(n*25.4-d.F)<1e-8)&&[425,450].includes(d.B)));
assert.equal(candidates({...item,dimensions:{B:fixed(300)}},s,barrel,capacity).length,0);
const rules=normalizeSizeRules([{F:48,B:24,unit:'in'}]);
options=candidates({...item,dimensions:{F:fixed(48,'in')}},{...s,sizeRules:rules},barrel,capacity);
assert.ok(options.length);assert.ok(options.every(d=>d.B>=609.6));
assert.equal(candidates({...item,dimensions:{F:fixed(48,'in'),B:fixed(600)}},{...s,sizeRules:rules},barrel,capacity).length,0);
assert.throws(()=>normalizeDimensions({F:{mode:'fixed',value:'35, 40'}}));
assert.throws(()=>normalizeDimensions({W:{mode:'range',value:'100, 200, 0'}}));
assert.throws(()=>normalizeDimensions({B:{mode:'options',value:'Infinity'}}));
const stock=normalizeInventory([{id:'Stock A',unit:'in',F:48,B:24,W:24,outer:27,t:1,tare:75,maxLoad:2000,qty:3}]);
const stockSettings={...s,inventory:stock};
const stockItem={...item,source:'available'};
options=candidates(stockItem,stockSettings,barrel,capacity);assert.equal(options.length,1);assert.equal(options[0].inventoryId,'Stock A');assert.equal(options[0].tare,75);assert.ok(Math.abs(options[0].outer-685.8)<1e-8);
assert.equal(candidates({...stockItem,stockId:'Missing'},stockSettings,barrel,capacity).length,0);
assert.equal(candidates({...stockItem,qty:4},stockSettings,barrel,capacity).length,0);
assert.equal(candidates({...stockItem,kg:100},stockSettings,barrel,capacity).length,0);
assert.equal(candidates({...stockItem,dimensions:{F:fixed(40,'in')}},stockSettings,barrel,capacity).length,0);
let plan=solve([stockItem,{...stockItem,name:'Other'}],stockSettings,barrel,capacity);
assert.equal(plan.placed.length,2);assert.equal(plan.missed,2);assert.equal(plan.chosen.filter(Boolean).length,1);
plan=solve([stockItem,{...item,name:'Other',source:'either'}],stockSettings,barrel,capacity);
assert.equal(plan.missed,0);assert.equal(plan.chosen.filter(d=>d.inventoryId).length,1);
plan=solve([stockItem],stockSettings,barrel,capacity);
assert.equal(planWeight([stockItem],plan.chosen,stockSettings).weight,370); // 2 * (100 + 75) + packing
assert.equal(planWeight([{...stockItem,kg:null}],plan.chosen,stockSettings).known,false);
assert.equal(planWeight([stockItem],plan.chosen,{...stockSettings,payload:369}).over,true);
const noTare=normalizeInventory([{...stock[0],tare:null}]);
plan=solve([stockItem],{...stockSettings,inventory:noTare},barrel,capacity);
assert.equal(planWeight([stockItem],plan.chosen,stockSettings).known,false);
const dimensions=normalizeDimensions({F:fixed(48,'in'),W:{mode:'range',unit:'mm',value:'600, 900, 25'}});
const backup=ctx.api.makeBackup({items:[{...stockItem,dimensions}],s:{...stockSettings,sizeRules:rules},barrelFormula:'m*od',capacityFormula:'k*W*((F-2*c)^2-B^2)/(1000*od^2)',containerType:'20'},[{...item,dimensions}]);
const restored=ctx.api.normalizeBackup(JSON.parse(JSON.stringify(backup)));
assert.equal(restored.plan.items[0].dimensions.F.unit,'in');assert.equal(restored.plan.items[0].source,'available');assert.equal(restored.plan.s.inventory[0].qty,3);assert.equal(restored.plan.s.sizeRules[0].B,24);assert.equal(restored.cableLibrary[0].dimensions.W.mode,'range');
delete backup.plan.s.inventory;delete backup.plan.s.sizeRules;delete backup.plan.items[0].dimensions;delete backup.plan.items[0].source;
const old=ctx.api.normalizeBackup(backup);assert.equal(old.plan.items[0].source,'custom');assert.equal(old.plan.items[0].dimensions.F.mode,'calculate');assert.equal(old.plan.s.inventory.length,0);
assert.throws(()=>normalizeInventory([{...stock[0],outer:20}]));assert.throws(()=>normalizeInventory([stock[0],stock[0]]));assert.throws(()=>normalizeInventory([{...stock[0],qty:1.5}]));
// Stock-specific flange thickness stays within the reserved geometry.
plan=solve([stockItem],stockSettings,barrel,capacity);
for(const face of ctx.api.modelGeometry(plan,stockSettings))for(const p of face.points){const d=face.drum;assert.ok(p[0]>=d.y-1e-7&&p[0]<=d.y+d.depth+1e-7);assert.ok(p[1]>=d.x-1e-7&&p[1]<=d.x+d.breadth+1e-7);}
console.log('PASS: exact inch/mm dimensions; lists/ranges; barrel minima by flange; stock matching, quantity contention and either-source fallback; stock weight checks; backup compatibility; inventory validation and 3D bounds.');
